version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
  working_directory: ~/mern-starter
  docker:
    - image: circleci/node:10.16.3
    - image: mongo:4.2.0
  steps:
  - checkout
  - run:
    name: install npm
    command: npm install
  - run:
    name: test
    command: npm test
  - run:
   name: code-coverage
   command: './node_modules/.bin/nyc report --reporter=text-lcov'
  - store_test_results:
    path: test-results.xml
